data <- "./data/household_power_consumption.txt"
data <- read.table(dataFile, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
power <- subset(data, Date=="1/2/2007"|Date=="2/2/2007")
gap <- as.numeric(power$Global_active_power)
datetime<-strptime(paste(power$Date,power$Time,sep=" "),"%d/%m/%Y %H:%M:%S")
sm1<-as.numeric(power$Sub_metering_1)
sm2<-as.numeric(power$Sub_metering_2)
sm3<-as.numeric(power$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(datetime,sm1,type="l",xlab="",ylab="Energy sub metering")
lines(datetime,sm2,type="l",col="red")
lines(datetime,sm3,type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,lwd=2.5,col=c("Black","Red","Blue"))
dev.off()
